### ISSUE TITLE
Animated images Support

### ISSUE THREAD

**Issue by Rajaniraiyn** [ElMassimo/vite-plugin-image-presets#11]
Sharp supports `animated` option to read all frames of an animated png, gif, avif, webp image formats. But, there is no way to use that option in presets. Now by default all animated images are converted to non-animated upon any conversion.

https://github.com/Rajaniraiyn/modern-web-boilerplate , this project uses apng but upon using this plugin it is converted into non-animated form.

Not only this. It would be nicer to enable an option to parse custom options to sharp

**Comment by ElMassimo** [comment]
Hi!

The default presets provide a `withImage` option, which you can use to access the Sharp instance and further customize it.

---

If you need more control, you can also [create your own presets](https://github.com/ElMassimo/vite-plugin-image-presets/blob/main/src/types.ts#L44).

You can use the [default presets](https://github.com/ElMassimo/vite-plugin-image-presets/blob/main/src/presets.ts#L40) as a starting point to create your own.
